fixed startup behaviour (healthchecks), added scripts

diff --git a/heroes/run-hero-create-specification b/heroes/run-hero-create-specification
--- a/heroes/run-hero-create-specification
+++ b/heroes/run-hero-create-specification
@@ -1,8 +1,22 @@
 #!/bin/bash
-echo "Starting tutorial Hero Crete Specification."
+trap "exit 1" TERM
+export TOP_PID=$$
+
+function failed_to_start() {
+  echo
+  echo "Failed to start test-editor-web ..."
+  echo "Stopping half started containers ..."
+  docker-compose down
+  echo "Stopped containers."
+  echo "Please retry with the now completely downloaded images."
+  echo "It should start (much) faster."
+  kill -s TERM $TOP_PID
+}
+
+echo "Starting tutorial Hero Create Specification."
 echo
 echo "If unresponse for too long (> 30 seconds), abort by pressing ctrl-c."
-sleep 2
+sleep 3
 
 BRANCH=hero-create-specification docker-compose up > te.log &
 CNT=0
@@ -15,13 +29,10 @@ do
    if [ "$TCNT" -eq 1 ]; then
      echo "Starting up backends (initialize java, dropwizard, gradle) ..."
    fi
-   if [ "$CNT" -eq 1 ]; then
-      echo -n "  ."
-   else
-      echo -n "."
-   fi
+   echo -n "."
    if [ "$CNT" -gt 35 ]; then CNT=0; echo ""; fi
    echo $LOGLINE | grep -q -e "xtext_1.*INFO.*org.eclipse.jetty.server.Server: Started @.*ms" && pkill -P $$ tail
+   echo $LOGLINE | grep -q -e "xtext_1 exited with code" && pkill -P $$ tail && failed_to_start
 done
 echo ""
 echo "Backends initialized."
@@ -32,15 +43,18 @@ CHROME=$(which chrome 2> /dev/null)
 CHROMIUM=$(which chromium-browser 2> /dev/null)
 
 if [ "$FIREFOX" != "" ]; then
-  echo "firefox ..."
+  echo "firefox ..." &
   $FIREFOX http://localhost:4200
 elif [ "$CHROMIUM" != "" ]; then
-  echo "chromium ..."
+  echo "chromium ..." &
   $CHROMIUM http://localhost:4200
 elif [ "$CHROME" != "" ]; then
   echo "firefox ..."
-  $CHROME http://localhost:4200
+  $CHROME http://localhost:4200 &
 else
   echo "browser failed."
   echo "No valid browser found."
+  exit 1
 fi
+echo "Started test-editor-web"
+exit 0
